name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change if you use a different default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll
        run: |
          gem install bundler
          bundle install || bundle init && bundle add jekyll

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          SITE_TOKEN: ${{ secrets.SITE_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_WEBSITE }}
          publish_dir: ./_site
